### ISSUE TITLE
Youtube video unavailable

### ISSUE THREAD

**Issue by mikecheng2626** [AgP42/MMM-iFrame-Ping#17]
I'm trying to set up streaming on my playlist of MTVs from my YouTube account

Followed the instruction...
1. 1st video of the playlist --> copy embed code
2. Copy the link after src
3. Did the autoplay and loop
4. Ex. LINK&autoplay=1&loop=1
5. Boot Magic Mirror.
6. Everything looks great except for the video where it shows the video is unavailable, go to YouTube website to watch it
7. What should I do??

Thank you,
Mike

**Comment by AgP42** [comment]
Duplicated. Closed, see #18
