### ISSUE TITLE
Impossible to connect with self signed certificate

### ISSUE THREAD

**Issue by Nesousx** [AgP42/MMM-iFrame-Ping#3]
Hi,

Many thanks for the module.

I might have stumbled upon an issue. It looks like the module can't open any webpage that uses a self signed certificate. Could this behavior be changed please?

Thanks in advance.

**Comment by AgP42** [comment]
Hello, 

infortunatelly several website doesn't support to be embedded into a iFrame, you can test your page here : 
[https://jsfiddle.net/westonruter/6mSuK/](https://jsfiddle.net/westonruter/6mSuK/)

If not compatible, then infortunatelly I cannot do anything... sorry !

Bye, 
AgP

**Comment by Nesousx** [comment]
Hi,

Thanks for your answer. However, it seems directly related to self signed HTTPS, the exact same website (LibreNMS monitoring): 

* is working with a "regular" HTTPS certif ; 
* it also works with HTTP ;
* but it won't work with self signed certif (which I need to have in this use case).
