### ISSUE TITLE
src has embedded border, can you add setting for 'seamless' ?

### ISSUE THREAD

**Issue by TheStigh** [AgP42/MMM-iFrame-Ping#7]
Hi,

A stream I do has a border, and I can't add a css entry to remove it (?):

User agent stylesheet:
iframe {
    border-width: 2px;
    border-style: inset;
    border-color: initial;
    border-image: initial;
}

Is there any other way I can have this border removed?

**Comment by AgP42** [comment]
Hello, 

did you check this ? : 
[https://forum.magicmirror.builders/topic/8481/mmm-iframe-ping/5](https://forum.magicmirror.builders/topic/8481/mmm-iframe-ping/5)

**Comment by TheStigh** [comment]
Solved it! :)
